### ISSUE TITLE
User-can-see-their-car

### ISSUE THREAD

**Issue by aaron-j-butnik** [aaron-j-butnik/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x]  Add div to hold car.
- [x] Find image to use as car.
- [x] Ensure that car image is showing up on page.
- [x] Remove all CSS styling that had no affect or was unnecessary
- [x] Check for bugs/fix all errors
